const DAYS = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const CATS = ['Produce','Meat & Seafood','Dairy & Eggs','Bakery','Pantry','Frozen','Drinks','Household','Other'];

const MEALS = [
  {name:'Chicken Tacos', tags:['mexican','chicken'], costPerServing:2.75, ingredients:[['Chicken breast',1.25,'lb','Meat & Seafood','decimal'],['Tortillas',8,'tortillas','Bakery','ceil'],['Shredded cheese',1.5,'cups','Dairy & Eggs','decimal'],['Lettuce',0.5,'head','Produce','ceil'],['Tomatoes',2,'tomatoes','Produce','ceil'],['Taco seasoning',1,'packet','Pantry','ceil'],['Salsa',1,'jar','Pantry','ceil']]},
  {name:'Beef Tacos', tags:['mexican','beef'], costPerServing:3.10, ingredients:[['Ground beef',1.25,'lb','Meat & Seafood','decimal'],['Tortillas',8,'tortillas','Bakery','ceil'],['Shredded cheese',1.5,'cups','Dairy & Eggs','decimal'],['Lettuce',0.5,'head','Produce','ceil'],['Tomatoes',2,'tomatoes','Produce','ceil'],['Taco seasoning',1,'packet','Pantry','ceil'],['Salsa',1,'jar','Pantry','ceil']]},
  {name:'Spaghetti with Meat Sauce', tags:['pasta','beef'], costPerServing:2.40, ingredients:[['Spaghetti',12,'oz','Pantry','decimal'],['Ground beef',1,'lb','Meat & Seafood','decimal'],['Pasta sauce',1,'jar','Pantry','ceil'],['Parmesan cheese',0.5,'cup','Dairy & Eggs','decimal'],['Garlic bread',1,'loaf','Bakery','ceil']]},
  {name:'Spaghetti Marinara', tags:['pasta','vegetarian'], costPerServing:1.55, ingredients:[['Spaghetti',12,'oz','Pantry','decimal'],['Pasta sauce',1,'jar','Pantry','ceil'],['Parmesan cheese',0.5,'cup','Dairy & Eggs','decimal'],['Garlic bread',1,'loaf','Bakery','ceil']]},
  {name:'Sheet Pan Chicken and Vegetables', tags:['chicken','one-pan'], costPerServing:3.25, ingredients:[['Chicken thighs',1.5,'lb','Meat & Seafood','decimal'],['Potatoes',1.5,'lb','Produce','decimal'],['Broccoli',1,'lb','Produce','decimal'],['Carrots',0.75,'lb','Produce','decimal'],['Olive oil',2,'tbsp','Pantry','decimal']]},
  {name:'Slow Cooker Chili', tags:['beef','slow-cooker'], costPerServing:2.65, ingredients:[['Ground beef',1,'lb','Meat & Seafood','decimal'],['Kidney beans',2,'cans','Pantry','ceil'],['Diced tomatoes',2,'cans','Pantry','ceil'],['Tomato sauce',1,'can','Pantry','ceil'],['Onion',1,'onion','Produce','ceil'],['Chili seasoning',1,'packet','Pantry','ceil']]},
  {name:'Bean and Cheese Burritos', tags:['mexican','vegetarian','budget'], costPerServing:1.30, ingredients:[['Flour tortillas',8,'tortillas','Bakery','ceil'],['Refried beans',2,'cans','Pantry','ceil'],['Shredded cheese',2,'cups','Dairy & Eggs','decimal'],['Salsa',1,'jar','Pantry','ceil'],['Rice',1.5,'cups','Pantry','decimal']]},
  {name:'Breakfast for Dinner', tags:['breakfast','budget'], costPerServing:1.45, ingredients:[['Eggs',10,'eggs','Dairy & Eggs','ceil'],['Pancake mix',2,'cups','Pantry','decimal'],['Milk',1.5,'cups','Dairy & Eggs','decimal'],['Breakfast sausage',0.75,'lb','Meat & Seafood','decimal'],['Bananas',4,'bananas','Produce','ceil']]},
  {name:'Grilled Cheese and Tomato Soup', tags:['sandwich','budget'], costPerServing:1.65, ingredients:[['Sandwich bread',1,'loaf','Bakery','ceil'],['Sliced cheese',12,'slices','Dairy & Eggs','ceil'],['Tomato soup',2,'cans','Pantry','ceil'],['Butter',4,'tbsp','Dairy & Eggs','decimal']]},
  {name:'Chicken Alfredo', tags:['pasta','chicken'], costPerServing:3.15, ingredients:[['Fettuccine',12,'oz','Pantry','decimal'],['Chicken breast',1.25,'lb','Meat & Seafood','decimal'],['Alfredo sauce',1,'jar','Pantry','ceil'],['Broccoli',0.75,'lb','Produce','decimal'],['Parmesan cheese',0.5,'cup','Dairy & Eggs','decimal']]},
  {name:'Baked Ziti', tags:['pasta','vegetarian'], costPerServing:2.05, ingredients:[['Ziti pasta',12,'oz','Pantry','decimal'],['Pasta sauce',1,'jar','Pantry','ceil'],['Ricotta cheese',1,'cup','Dairy & Eggs','decimal'],['Mozzarella cheese',2,'cups','Dairy & Eggs','decimal']]},
  {name:'Chicken Fried Rice', tags:['rice','chicken'], costPerServing:2.05, ingredients:[['Chicken breast',1,'lb','Meat & Seafood','decimal'],['Rice',2,'cups','Pantry','decimal'],['Frozen mixed vegetables',1,'bag','Frozen','ceil'],['Eggs',3,'eggs','Dairy & Eggs','ceil'],['Soy sauce',0.25,'cup','Pantry','decimal']]},
  {name:'Black Bean Quesadillas', tags:['mexican','vegetarian','budget'], costPerServing:1.40, ingredients:[['Flour tortillas',8,'tortillas','Bakery','ceil'],['Black beans',2,'cans','Pantry','ceil'],['Shredded cheese',2,'cups','Dairy & Eggs','decimal'],['Salsa',1,'jar','Pantry','ceil'],['Bell peppers',2,'peppers','Produce','ceil']]},
  {name:'Sloppy Joes', tags:['beef','sandwich'], costPerServing:2.25, ingredients:[['Ground beef',1.25,'lb','Meat & Seafood','decimal'],['Sloppy joe sauce',1,'can','Pantry','ceil'],['Hamburger buns',8,'buns','Bakery','ceil'],['Carrots',1,'lb','Produce','decimal']]},
  {name:'Baked Chicken Drumsticks', tags:['chicken','oven'], costPerServing:2.35, ingredients:[['Chicken drumsticks',2,'lb','Meat & Seafood','decimal'],['Potatoes',1.5,'lb','Produce','decimal'],['Green beans',1,'lb','Produce','decimal'],['BBQ sauce',1,'bottle','Pantry','ceil']]},
  {name:'Sausage and Peppers', tags:['sausage','one-pan'], costPerServing:2.75, ingredients:[['Italian sausage',1.25,'lb','Meat & Seafood','decimal'],['Bell peppers',3,'peppers','Produce','ceil'],['Onion',1,'onion','Produce','ceil'],['Rice',1.5,'cups','Pantry','decimal']]},
  {name:'Chicken Noodle Soup', tags:['soup','chicken','budget'], costPerServing:1.85, ingredients:[['Chicken breast',1,'lb','Meat & Seafood','decimal'],['Egg noodles',8,'oz','Pantry','decimal'],['Chicken broth',2,'cartons','Pantry','ceil'],['Carrots',0.75,'lb','Produce','decimal'],['Celery',0.5,'bunch','Produce','ceil'],['Onion',1,'onion','Produce','ceil']]},
  {name:'Loaded Baked Potatoes', tags:['vegetarian','budget'], costPerServing:1.35, ingredients:[['Russet potatoes',4,'potatoes','Produce','ceil'],['Shredded cheese',1.5,'cups','Dairy & Eggs','decimal'],['Sour cream',1,'container','Dairy & Eggs','ceil'],['Broccoli',0.75,'lb','Produce','decimal'],['Green onions',1,'bunch','Produce','ceil']]},
  {name:'Tuna Pasta Bake', tags:['pasta','seafood','budget'], costPerServing:1.75, ingredients:[['Pasta',12,'oz','Pantry','decimal'],['Canned tuna',3,'cans','Pantry','ceil'],['Cream of mushroom soup',2,'cans','Pantry','ceil'],['Frozen peas',1,'bag','Frozen','ceil'],['Shredded cheese',1.5,'cups','Dairy & Eggs','decimal']]},
  {name:'Homemade Pizza', tags:['pizza','family-favorite'], costPerServing:2.30, ingredients:[['Pizza dough',2,'dough balls','Bakery','ceil'],['Pizza sauce',1,'jar','Pantry','ceil'],['Mozzarella cheese',2.5,'cups','Dairy & Eggs','decimal'],['Pepperoni',1,'pack','Meat & Seafood','ceil'],['Bell pepper',1,'pepper','Produce','ceil']]},
  {name:'Chicken and Rice Casserole', tags:['chicken','casserole'], costPerServing:2.20, ingredients:[['Chicken breast',1.25,'lb','Meat & Seafood','decimal'],['Rice',1.5,'cups','Pantry','decimal'],['Cream of chicken soup',2,'cans','Pantry','ceil'],['Frozen mixed vegetables',1,'bag','Frozen','ceil'],['Shredded cheese',1,'cup','Dairy & Eggs','decimal']]},
  {name:'Lentil Tacos', tags:['mexican','vegetarian','budget'], costPerServing:1.10, ingredients:[['Dry lentils',1.5,'cups','Pantry','decimal'],['Tortillas',8,'tortillas','Bakery','ceil'],['Shredded cheese',1.5,'cups','Dairy & Eggs','decimal'],['Lettuce',0.5,'head','Produce','ceil'],['Salsa',1,'jar','Pantry','ceil'],['Taco seasoning',1,'packet','Pantry','ceil']]},
  {name:'Vegetable Stir Fry with Rice', tags:['vegetarian','rice','budget'], costPerServing:1.45, ingredients:[['Rice',2,'cups','Pantry','decimal'],['Frozen stir fry vegetables',2,'bags','Frozen','ceil'],['Soy sauce',0.25,'cup','Pantry','decimal'],['Eggs',4,'eggs','Dairy & Eggs','ceil']]},
  {name:'Turkey Burgers and Oven Fries', tags:['turkey','sandwich'], costPerServing:2.80, ingredients:[['Ground turkey',1.25,'lb','Meat & Seafood','decimal'],['Hamburger buns',8,'buns','Bakery','ceil'],['Potatoes',2,'lb','Produce','decimal'],['Lettuce',0.5,'head','Produce','ceil'],['Tomatoes',2,'tomatoes','Produce','ceil']]}
];

let state={days:{},custom:[],checked:{}}; DAYS.forEach(d=>state.days[d]={meal:'',notes:'',ingredients:[]});
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const byId=id=>document.getElementById(id); const familyCount=()=>Math.max(1,Number(byId('familySize')?.value||4)); const budgetValue=()=>Math.max(0,Number(byId('budget')?.value||0));
function mealMatch(name){const q=String(name||'').trim().toLowerCase();if(!q)return null;return MEALS.find(m=>m.name.toLowerCase()===q)||MEALS.find(m=>m.name.toLowerCase().includes(q))||MEALS.find(m=>q.includes(m.name.toLowerCase()));}
function formatNumber(n){if(Number.isInteger(n))return String(n);if(Math.abs(n*2-Math.round(n*2))<.001)return String(Math.round(n*2)/2);return String(Math.round(n*10)/10);}
function scaledQty(baseQty,unit,mode,size){let value=baseQty*(size/4);if(mode==='ceil')value=Math.ceil(value);else if(mode==='whole')value=Math.max(1,Math.round(value));else value=Math.max(.1,Math.round(value*10)/10);const singular={cans:'can',cartons:'carton',eggs:'egg',tortillas:'tortilla',buns:'bun',bananas:'banana',tomatoes:'tomato',peppers:'pepper','dough balls':'dough ball'};return `${formatNumber(value)} ${value===1&&singular[unit]?singular[unit]:unit}`.trim();}
function suggestedIngredients(meal){const size=familyCount();return meal.ingredients.map(([name,qty,unit,category,mode])=>({name,qty:scaledQty(qty,unit,mode,size),category,sourceMeal:meal.name}));}
function estimateMealCost(meal,size=familyCount()){return meal?meal.costPerServing*size:0;} function estimatePlanCost(){return DAYS.reduce((sum,d)=>sum+estimateMealCost(mealMatch(state.days[d].meal)),0);} function mealOptions(){return MEALS.map(m=>`<option value="${esc(m.name)}"></option>`).join('');}
function renderPlanner(){const root=byId('plannerGrid');root.innerHTML='';DAYS.forEach(day=>{const d=state.days[day],match=mealMatch(d.meal),card=document.createElement('article');card.className='meal-card';card.innerHTML=`<div class="meal-card-header"><b>${day}</b><span>${match?`Est. $${estimateMealCost(match).toFixed(0)}`:'Dinner'}</span></div><input list="meal-library" placeholder="Type or choose a meal" value="${esc(d.meal)}" oninput="setDay('${day}','meal',this.value)" onblur="maybeSuggest('${day}')"><div class="meal-assist-row"><button class="small-btn" onclick="suggestForDay('${day}')">✨ Suggest ingredients</button>${match?`<small>${esc(match.name)} matched · scaled for ${familyCount()}</small>`:'<small>Choose a suggested meal for automatic quantities.</small>'}</div><textarea placeholder="Optional notes: leftovers, prep ahead…" oninput="setDay('${day}','notes',this.value)">${esc(d.notes)}</textarea><div class="ingredients-box"><strong>Ingredients to buy</strong><div id="ingredients-${day}"></div><button class="small-btn" onclick="addIngredient('${day}')">+ Add ingredient</button></div>`;root.appendChild(card);renderIngredients(day);});}
function renderIngredients(day){const r=byId('ingredients-'+day);if(!r)return;r.innerHTML='';state.days[day].ingredients.forEach((it,i)=>{const row=document.createElement('div');row.className='ingredient-row';row.innerHTML=`<input placeholder="Ingredient" value="${esc(it.name)}" oninput="updateIngredient('${day}',${i},'name',this.value)"><input placeholder="Qty" value="${esc(it.qty)}" oninput="updateIngredient('${day}',${i},'qty',this.value)"><select onchange="updateIngredient('${day}',${i},'category',this.value)">${CATS.map(c=>`<option ${c===it.category?'selected':''}>${c}</option>`).join('')}</select><button class="icon-btn" onclick="removeIngredient('${day}',${i})" aria-label="Remove ingredient">×</button>`;r.appendChild(row);});if(!state.days[day].ingredients.length)r.innerHTML='<small>No ingredients added yet.</small>';}
function setDay(day,key,value){state.days[day][key]=value;save();renderGrocery();updateGeneratorSummary();}
function maybeSuggest(day){const d=state.days[day],match=mealMatch(d.meal);if(match&&d.ingredients.length===0)suggestForDay(day,false);} function suggestForDay(day,notify=true){const match=mealMatch(state.days[day].meal);if(!match){if(notify)alert('Choose a meal from the suggestions first, or type a meal name that closely matches one in the library.');return;}state.days[day].meal=match.name;state.days[day].ingredients=suggestedIngredients(match);renderPlanner();renderGrocery();save();if(notify)toast(`${match.name} ingredients added for ${familyCount()} people.`);}
function rescaleSuggestedIngredients(){DAYS.forEach(day=>{const match=mealMatch(state.days[day].meal);if(!match)return;const hasSuggested=state.days[day].ingredients.some(i=>i.sourceMeal===match.name);if(hasSuggested)state.days[day].ingredients=suggestedIngredients(match);});renderPlanner();renderGrocery();save();}
function addIngredient(day,it={name:'',qty:'',category:'Pantry'}){state.days[day].ingredients.push(it);renderIngredients(day);save();renderGrocery();} function updateIngredient(day,i,key,value){state.days[day].ingredients[i][key]=value;save();renderGrocery();} function removeIngredient(day,i){state.days[day].ingredients.splice(i,1);renderIngredients(day);save();renderGrocery();}
function addCustomItem(){const name=byId('customItem').value.trim();if(!name)return;state.custom.push({name,qty:byId('customQty').value.trim(),category:byId('customCategory').value});byId('customItem').value='';byId('customQty').value='';save();renderGrocery();}
function groceryItems(){const all=[];DAYS.forEach(d=>state.days[d].ingredients.forEach(i=>{if(i.name.trim())all.push({...i});}));state.custom.forEach(i=>{if(i.name.trim())all.push({...i});});const map=new Map();all.forEach(i=>{const key=i.category+'|'+i.name.trim().toLowerCase();if(!map.has(key))map.set(key,{...i,name:i.name.trim(),qtys:[]});if(i.qty&&!map.get(key).qtys.includes(i.qty))map.get(key).qtys.push(i.qty);});return[...map.values()].map(i=>({...i,qty:i.qtys.join(' + ')}));}
function renderGrocery(){const items=groceryItems(),root=byId('groceryGroups');root.innerHTML='';CATS.forEach(cat=>{const list=items.filter(i=>i.category===cat);if(!list.length)return;const section=document.createElement('section');section.className='grocery-group';section.innerHTML=`<h3>${cat}</h3>`;list.forEach(i=>{const id=cat+'|'+i.name.toLowerCase(),row=document.createElement('label');row.className='grocery-item '+(state.checked[id]?'done':'');row.innerHTML=`<input type="checkbox" ${state.checked[id]?'checked':''} onchange="toggleChecked('${encodeURIComponent(id)}',this.checked)"><span>${esc(i.name)}</span><small>${esc(i.qty)}</small>`;section.appendChild(row);});root.appendChild(section);});if(!items.length)root.innerHTML='<p>Your grocery list is empty. Choose meals and use “Suggest ingredients,” or generate a full week automatically.</p>';byId('mealCount').textContent=DAYS.filter(d=>state.days[d].meal.trim()).length;byId('itemCount').textContent=items.length;const budget=budgetValue(),estimate=estimatePlanCost();if(estimate>0)byId('budgetSummary').innerHTML=`Estimated dinner ingredients: <strong>$${estimate.toFixed(0)}</strong>${budget?` of $${budget.toFixed(0)} target`:''}<br><small>Planning estimate only; local prices vary.</small>`;else byId('budgetSummary').textContent=budget?`Target grocery budget: $${budget.toFixed(0)}`:'Add an optional budget above.';}
function toggleChecked(x,v){state.checked[decodeURIComponent(x)]=v;save();renderGrocery();} function snapshot(){return{state,planName:byId('planName').value,familySize:byId('familySize').value,budget:byId('budget').value};} function save(show=false){localStorage.setItem('familyMealPlanner',JSON.stringify(snapshot()));if(show)toast('Saved on this device.');} function loadSaved(){try{const x=JSON.parse(localStorage.getItem('familyMealPlanner'));if(!x)return;state=x.state||state;byId('planName').value=x.planName||'';byId('familySize').value=x.familySize||4;byId('budget').value=x.budget||'';}catch(e){}} function clearPlan(){if(!confirm('Clear this meal plan and grocery list?'))return;localStorage.removeItem('familyMealPlanner');location.reload();}
function buildText(){let text=(byId('planName').value.trim()||'My Family Meal Plan')+'\nFamily size: '+familyCount()+'\n';if(budgetValue())text+='Budget target: $'+budgetValue().toFixed(0)+'\n';if(estimatePlanCost())text+='Estimated dinner cost: $'+estimatePlanCost().toFixed(0)+'\n';text+='\nMEALS\n-----\n';DAYS.forEach(d=>{const x=state.days[d];if(x.meal.trim())text+=d+': '+x.meal+(x.notes?' — '+x.notes:'')+'\n';});text+='\nGROCERY LIST\n------------\n';const items=groceryItems();CATS.forEach(c=>{const list=items.filter(i=>i.category===c);if(list.length){text+='\n'+c+'\n';list.forEach(i=>text+='[ ] '+i.name+(i.qty?' — '+i.qty:'')+'\n');}});text+='\nRecipe ideas: https://themanthatcookssometimes.blogspot.com/';return text;} async function copyList(){try{await navigator.clipboard.writeText(buildText());toast('Plan and grocery list copied.');}catch(e){prompt('Copy your list:',buildText());}} function emailList(){location.href='mailto:?subject='+encodeURIComponent((byId('planName').value.trim()||'My Family Meal Plan')+' + Grocery List')+'&body='+encodeURIComponent(buildText());}
function pickPlan(size,budget){const target=budget>0?budget:95*(size/4),meals=[...MEALS].sort((a,b)=>a.costPerServing-b.costPerServing);let selected=meals.slice(0,7),total=selected.reduce((s,m)=>s+estimateMealCost(m,size),0);const usedTags=new Set(selected.flatMap(m=>m.tags)),remaining=meals.filter(m=>!selected.includes(m));for(const candidate of remaining){const candidateCost=estimateMealCost(candidate,size);let bestIndex=-1,bestGain=-Infinity;selected.forEach((current,i)=>{const newTotal=total-estimateMealCost(current,size)+candidateCost;if(newTotal>target)return;const novelty=candidate.tags.filter(t=>!usedTags.has(t)).length,sameness=current.tags.some(t=>candidate.tags.includes(t))?-.5:.5,gain=novelty+sameness+(candidate.costPerServing-current.costPerServing)*.08;if(gain>bestGain){bestGain=gain;bestIndex=i;}});if(bestIndex>=0){selected[bestIndex]=candidate;total=selected.reduce((s,m)=>s+estimateMealCost(m,size),0);usedTags.clear();selected.forEach(m=>m.tags.forEach(t=>usedTags.add(t)));}}selected.sort((a,b)=>a.tags[0].localeCompare(b.tags[0]));return{selected,total,target,minPossible:meals.slice(0,7).reduce((s,m)=>s+estimateMealCost(m,size),0)};}
function generateMealPlan(){const size=familyCount(),budget=budgetValue(),{selected,total,minPossible}=pickPlan(size,budget);DAYS.forEach((day,i)=>{const meal=selected[i];state.days[day]={meal:meal.name,notes:'',ingredients:suggestedIngredients(meal)};});byId('planName').value=`Generated ${size}-Person Meal Plan`;state.checked={};renderPlanner();renderGrocery();save();updateGeneratorSummary();if(budget&&minPossible>budget)toast(`Generated the lowest-cost mix available. Estimated dinners are $${total.toFixed(0)}, above the $${budget.toFixed(0)} target.`,'warn');else toast(`Generated 7 dinners for about $${total.toFixed(0)} in estimated ingredients.`);document.querySelector('#planner').scrollIntoView({behavior:'smooth'});}
function updateGeneratorSummary(){const box=byId('generatorStatus');if(!box)return;const size=familyCount(),budget=budgetValue(),estimate=estimatePlanCost();box.textContent=estimate?`Current plan estimate: $${estimate.toFixed(0)} for ${size} people${budget?` · budget target $${budget.toFixed(0)}`:''}.`:`Set your family size${budget?' and budget':''}, then generate a full seven-night plan.`;}
function loadExample(){byId('familySize').value=4;byId('budget').value=85;const names=['Chicken Tacos','Spaghetti with Meat Sauce','Sheet Pan Chicken and Vegetables','Black Bean Quesadillas','Homemade Pizza','Breakfast for Dinner','Slow Cooker Chili'];DAYS.forEach((d,i)=>{const meal=mealMatch(names[i]);state.days[d]={meal:meal.name,notes:'',ingredients:suggestedIngredients(meal)};});byId('planName').value='Example Family Week';renderPlanner();renderGrocery();save();updateGeneratorSummary();document.querySelector('#planner').scrollIntoView({behavior:'smooth'});}
function toast(message,type='ok'){let el=byId('plannerToast');if(!el){el=document.createElement('div');el.id='plannerToast';document.body.appendChild(el);}el.textContent=message;el.className='planner-toast '+type;el.classList.add('show');clearTimeout(window.__plannerToast);window.__plannerToast=setTimeout(()=>el.classList.remove('show'),3500);}
function init(){const data=document.createElement('datalist');data.id='meal-library';data.innerHTML=mealOptions();document.body.appendChild(data);loadSaved();renderPlanner();renderGrocery();updateGeneratorSummary();['planName','budget'].forEach(id=>byId(id).addEventListener('input',()=>{save();renderGrocery();updateGeneratorSummary();}));byId('familySize').addEventListener('change',()=>{rescaleSuggestedIngredients();updateGeneratorSummary();});byId('familySize').addEventListener('input',()=>{save();updateGeneratorSummary();});} init();